### ISSUE TITLE
AttributeError: 'Blob' object has no attribute 'mask'

### ISSUE THREAD

**Issue by emily19941102** [cs-chan/fuzzyDCN#2]
AttributeError: 'Blob' object has no attribute 'mask'  @cs-chan  thanks!

**Comment by willtwr** [comment]
Hi,

Please refer to the following paper to get the modified CAFFE library in order to use the mask attribute:

Han, S., Pool, J., Tran, J., & Dally, W. (2015). Learning both weights and connections for efficient neural network. In Advances in Neural Information Processing Systems (pp. 1135-1143).
